### ISSUE TITLE
Fails to compile with go 1.16.2/riscv

### ISSUE THREAD

**Issue by kraj** [simpleiot/simpleiot#160]
I am seeing this error

```
# github.com/dgraph-io/ristretto/z
../../../build/tmp/work-shared/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210122082011-bb5d392ed82d/z/btree.go:461:13: undefined: simd.Search
../../../build/tmp/work-shared/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210122082011-bb5d392ed82d/z/buffer.go:76:35: undefined: MaxBufferSize
WARNING: TOPDIR/build/tmp/work/riscv64-yoe-linux-musl/simpleiot/0.0.14+git999-r0/temp/run.do_compile.1330011:102 exit 1 from 'return 1'
```

see

https://errors.yoctoproject.org/Errors/Details/574032/

**Comment by cbrake** [comment]
I recently updated badger stuff to v3, so likely they broke something there.

**Comment by kraj** [comment]
yeah thats the cause, I have fixed it and sent a PR https://github.com/dgraph-io/ristretto/pull/262

**Comment by cbrake** [comment]
thanks @kraj

**Comment by cbrake** [comment]
@kraj I assume this has been fixed by now?

**Comment by kraj** [comment]
yes indeed.
